### ISSUE TITLE
Add options for defer async etc.

### ISSUE THREAD

**Issue by pfrlv** [Diverently/laravel-mix-kirby#5]
Maybe you should add `$options = []` to the mix function? I can make PR

**Comment by RobertCordes** [comment]
What do you think would be the better approach:
1. Add options to the mix function
2. Add a new function that only returns the path instead of the whole HTML tag

I'm currently leaning more towards option 2. It could be used like this:
```php
<script src="<?php echo mixPath('/main.js') ?>" async>
```

What's your opinion on this?

**Comment by jonasfeige** [comment]
I much prefer option 2 as well. Makes things less abstract.

**Comment by arnoson** [comment]
I tend to option 1 making the function behave like kirby's `js()` and `css()` helpers. Maybe it could be as simple as forwarding the options array to the helper functions?

**Comment by RobertCordes** [comment]
Thanks, @arnoson, didn’t think of that.
