### ISSUE TITLE
Manifest path on custom folder setup

### ISSUE THREAD

**Issue by jonasfeige** [Diverently/laravel-mix-kirby#8]
Hi there.

I am trying to use the Mix helper plugin on a Kirby installation with custom folder setup.
I am assigning the `assets root` where the `mix-manifest.json` can be found in the `index.php` like so:

```
$kirby = new Kirby([
  'roots' => [
    'assets'   => dirname(__DIR__, 2) . '/assets'
  ],
]);
```

Then setting the `manifestPath` of the plugin in the `config.php` like so:

```
return [
  'diverently.laravel-mix-kirby.manifestPath' => kirby()->root('assets') . '/mix-manifest.json',
];
```

This returns an absolute URL which during local development has a leading `/`. The `/`is removed by the plugin [here](https://github.com/Diverently/laravel-mix-kirby/blob/master/index.php#L47-L49), and I therefor get the error that `The Mix manifest does not exist.`.

Is there any way to work around this? Why does the `/` have to be removed?

Any help would be appreciated. I love the plugin and have used it many times, only now running into difficulties with the custom folder setup.

**Comment by RobertCordes** [comment]
Hi. I'm testing this right now and can't find the problem. Can you post your folder structure? :)

**Comment by jonasfeige** [comment]
Sure. It looks something like this:

```
kgb/
|── assets/
   |── app.css
   |── app.js
   |── mix-manifest.json
|── kirby/
|── site/
   |── blueprints/
   |── plugins/
   |── snippets/
   |── templates/
|── sites/
   |── siteOne/
      |── content/
      |── index.php // this is where the roots are set
      |── kirby/ (symlink)
      |── media/
      |── site/
   |── siteTwo/
   |── siteThree/
|── src/
   |── css/
   |── js/
```

**Comment by RobertCordes** [comment]
Thanks. I've never built a multisite setup with the [_alternative approach_](https://getkirby.com/docs/cookbook/setup/multisite-variant), so it’s gonna take me some time, which right now I, unfortunately, don’t have. I will try to get back to this next week.

**Comment by jonasfeige** [comment]
I’ve solved this by using a symlink instead of a custom root for the `assets` folder in the meantime. Much simpler, since that way I don’t have to configure anything within the mix-plugin.

**Comment by RobertCordes** [comment]
As you can see I didn't yet have the time to actually "fix" this. I tried, but couldn't get it to work as you expected :-/ But as you already found a workaround, I will close this for now. Feel free to reopen though!
